# Generated by Django 5.1.1 on 2024-10-04 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Death Date'),
        ),
        migrations.AlterField(
            model_name='author',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Pseudonym'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotecore.author', verbose_name='Authors'),
        ),
    ]
