# Generated by Django 5.1.1 on 2024-10-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotecore', '0002_alter_author_death_date_alter_author_pseudonym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Source'),
        ),
    ]
